method: onet_conv
data:
  path: data/ShapeNet
  img_folder: img_choy2016
  img_size: 256 
  points_subsample: 2048 
model:
  encoder_latent: null
  # decoder: cbatchnorm
  decoder: simple_local      
  decoder_kwargs:
    sample_mode: bilinear # bilinear / nearest
    hidden_size: 64
  c_dim: 64
  encoder: znet
  z_dim: 0
  output_nc : 64
  num_downs : 8
training:
  out_dir:  out/img/onet_conv_64
  batch_size: 1
  model_selection_metric: iou
  model_selection_mode: maximize
  visualize_every: 10000
  validate_every: 10000
test:
  threshold: 0.2
  eval_mesh: true
  eval_pointcloud: false
generation:
  batch_size: 100000
  refine: false
  n_x: 128
  n_z: 1
  resolution_0: 32 
  upsampling_steps: 2 ddddf

